# GDM configuration storage

[daemon]
#WaylandEnable=false
AutomaticLoginEnable=True
AutomaticLogin=m
DefaultSession=gnome.desktop

[security]

[xdmcp]

[chooser]

[debug]
# Uncomment the line below to turn on debugging
#Enable=true
