#!/bin/bash

# this is changed via sed by darkman:
THEME_DARK=1

# set fzf options as global envs via sourcing this in .zshrc.
FZF_DEFAULT_OPTS_BASE="--style=minimal --no-info --no-separator --border=none --marker='█' --pointer='◆'"

# dark color palette:
FZF_DEFAULT_OPTS_DARK="--color=light --color=fg:#000000,fg+:#000000,bg:#FFFFFF,bg+:#FFFFFF,preview-bg:#FFFFFF,hl:#008080,hl+:#800080,info:#000000,marker:#800080,prompt:#800080,spinner:#330099,pointer:#800080,header:#000000,border:#000000,label:#000000,query:#000000,gutter:#FFFFFF"

# light color palette:
FZF_DEFAULT_OPTS_LIGHT="--color=dark --color=fg:#FAF0E6,fg+:#FAF0E6,bg:#000000,bg+:#1D1F21,preview-bg:#000000,hl:#00FFFF,hl+:#FF00FF,info:#FAF0E6,marker:#FF00FF,prompt:#FF00FF,spinner:#330099,pointer:#FF00FF,header:#FAF0E6,border:#FAF0E6,label:#FAF0E6,query:#FAF0E6,gutter:#000000"

# this composition is changed via sed by darkman:
export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS_BASE $FZF_DEFAULT_OPTS_DARK"


if [[ $THEME_DARK == true ]]
then
    export CALIBRE_USE_DARK_PALETTE=1

    export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS_BASE $FZF_DEFAULT_OPTS_DARK"

else
    export CALIBRE_USE_DARK_PALETTE=0

    export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS_BASE $FZF_DEFAULT_OPTS_LIGHT"
fi
